### ISSUE TITLE
Upgrade mobile styling of 508 color matrix

### ISSUE THREAD

**Issue by jenniferthibault** [18F/brand#100]
@rtwell mocked up some awesome mobile designs for our color matrix in https://github.com/18F/brand/issues/51#issuecomment-223129613

Thanks very much to @toolness for implementing a first iteration in https://github.com/18F/brand/pull/94 and suggesting we separate this into an upgrade issue.

Here's Ryan's work, ready for implementation
## Default view

![18f-brand-mobile_collapse](https://cloud.githubusercontent.com/assets/12564977/15726156/fc661892-2814-11e6-9f6b-b51a6dea9f3c.png)
## First color expanded

![18f-brand-mobile_expand](https://cloud.githubusercontent.com/assets/12564977/15726166/084b0154-2815-11e6-8d97-86eb5c30dd44.png)
## All expanded

![18f-brand-mobile_expand-all](https://cloud.githubusercontent.com/assets/12564977/15726208/33943ee8-2815-11e6-85b1-bb671864f565.png)

**Comment by cmajel** [comment]
To dos:

* Update with the url of where this lives

**Comment by Dahianna** [comment]
Solved with #244
