### ISSUE TITLE
Clarify when and how to use different logo formats appropriately

### ISSUE THREAD

**Issue by jenniferthibault** [18F/brand#102]
We made a new logo, yay!

After a few months of kicking the tires, some questions have come up about when to use what version of the logo, and over what color backgrounds. The guidance in https://github.com/18F/writing-lab/issues/177 is a first step in the right direction, but many design-oriented folks on our team could use more specific guidance in order to understand the rules behind the system, and implement it consistently.

**Common questions:**
- When should I use the black logo?
- When should I use the bright blue logo? 
- I see a white logo on the desktop background files, can I use that?
- If the white `18F` text on the bright blue logo isn't best practices, should we even offer that combination?
  - Designer note: If no, do we drop that version altogether, or edit the text color to meet best practices for color contrast?

These questions point to a need for more clarity, which could be reached through more specific guidance, or by adjusting the logo options we make available. (or both)

Thanks to @maya, @andrewmaier , @rtwell for surfacing points of confusion, offering suggestions, and great discussion [today in slack](https://18f.slack.com/archives/18f-branding/p1468430439000172).

**Comment by cmajel** [comment]
Next steps:
- review current guidance and determine what is still needed

**Comment by Dahianna** [comment]
Here's the current guidance: https://brand.18f.gov/logo/ It answers the questions above, but we might want to upload a bright blue logo fir download

**Comment by Dahianna** [comment]
@cmajel will create a blue logo and @Dahianna will update the page and create a PR
