### ISSUE TITLE
Google Docs templates feedback: Increase spacing after paragraph styles

### ISSUE THREAD

**Issue by jenniferthibault** [18F/brand#129]
After first circulating the templates with the design team, we got a few points of feedback on the default typography styles. This issue is for one theme.

## So that writers and editors don't need to add an an additional hard return between elements, set measured space after paragraphs
> ...everytime I create a Google Doc, I find myself adding paragraph space to Normal text for space between elements and to avoid having to use two carriage returns between paragraphs. So, what I'm saying is, I got a fever…and the only prescription…is more paragraph space.

> ...the present paragraph styles don’t have _any_ spacing after paragraphs, which means most folks are just going to hit `return` and leave a blank line between paragraphs

**Comment by austinhernandez** [comment]
The problem I'm running into here is that because bulleted lists use "normal text" styles they are inheriting the paragraph styles. There is no "bullet" class, so the spacing after a paragraph is applied to each bullet.

![image](https://cloud.githubusercontent.com/assets/23194720/25915413/02c43f5e-3587-11e7-8fe8-35f18fd1c9c3.png)

I knew there was an issue I ran into before, but I'm trying to troubleshoot.

**Comment by jenniferthibault** [comment]
I'd think it's right to also add that space following bullets to help offset the start of one from another. What if we keep it instead of trying to eliminate it? 

Example from a rando doc I have open:

<img width="810" alt="screen shot 2017-05-10 at 3 43 51 pm" src="https://cloud.githubusercontent.com/assets/11636908/25917869/807b19a8-3597-11e7-979d-74cdf36a6116.png">

**Comment by austinhernandez** [comment]
I think it just depends on the amount of spacing between the elements and which elements. 
IE:
![image](https://cloud.githubusercontent.com/assets/23194720/25925691/ce77e4f2-35af-11e7-9dc1-cb0767e57de4.png)
![image](https://cloud.githubusercontent.com/assets/23194720/25925817/ae79a284-35b0-11e7-9ef0-81ceac02d044.png)

**Comment by austinhernandez** [comment]
hrmmmph! @jenniferthibault or @amberwreed I updated the doc to address this issue but. [Doc here](https://docs.google.com/document/d/1BovRM6thz0YWCyd32zwbh-6TYy4ON6GEc8ILDd3RLl8/edit#) could I get extra design  👀 on it, please?

Also when applying the styles to [this doc I made](https://docs.google.com/document/d/1myEM5XQiylPqJzniepHf7btD7JeR9VkkHevNxr0t2hY/edit#) it doesn't apply normal styles to bullets or add paragraph spacing. Can you replicate this issue on new or existing docs?

**Comment by jenniferthibault** [comment]
@austinhernandez I've hit that issue before. Try first Resetting the styles, then try applying your default styles:
1. <img width="440" alt="screen shot 2017-05-11 at 4 10 32 pm" src="https://cloud.githubusercontent.com/assets/11636908/25969848/70e236ac-3664-11e7-9d59-eaad8c80fd7f.png">

2. <img width="465" alt="screen shot 2017-05-11 at 4 10 41 pm" src="https://cloud.githubusercontent.com/assets/11636908/25969854/757a1e46-3664-11e7-8793-f0139ec0f78c.png">

The adjustments feel good to me, I did a check for any lingering manual hard returns, and didn't see any except for the last credits page, which feels like a special kind of layout. So it looks to me like the type spacing is doing all the work we want it to through the built in styles. Nice!

@amberwreed , do you want to take a look?
