### ISSUE TITLE
Google Docs templates feedback: Adjust default spacing around heading styles

### ISSUE THREAD

**Issue by jenniferthibault** [18F/brand#130]
After first circulating the templates with the design team, we got a few points of feedback on the default typography styles. This issue is for one theme.

## So that page flow happens predictably and without editing effort, set predictable patterns for space above & below headlines

> ...can we default to always having more space above the headings than below them? For example, the “heading 3” styles don’t do this and it creates an awkward vertical rhythm.

**Comment by austinhernandez** [comment]
I addressed this issue with [129](https://github.com/18F/brand/issues/129)
