### ISSUE TITLE
TTS logos instead of 18F?

### ISSUE THREAD

**Issue by oghaffari** [18F/brand#133]
Is it possible to get TTS logos instead of 18F? For Office of Acquisition docs and presentations that don't involve 18F, it would be nice to either have a version of the docs with the TTS logos or a version of the TTS logo image that is appropriate (scale? colors? not sure what needs to be kept in mind) for us to swap it out ourselves.

Edit: In case it isn't clear, I'm referring to getting logos for [these amazing docs and presentations](https://brand.18f.gov/templates/).

**Comment by jenniferthibault** [comment]
Hi @oghaffari 👋 
I randomly saw a similar exchange in another doc, and it looks like it would apply here too. cc @awfrancisco

![screen shot 2017-05-25 at 2 06 53 pm](https://cloud.githubusercontent.com/assets/11636908/26499728/a3a9536a-4201-11e7-8546-4fda70a8a2ff.png)
