### ISSUE TITLE
For revised template - 508 compliant contrast

### ISSUE THREAD

**Issue by lauraGgit** [18F/brand#138]
some of the contrast in the older template was not sufficient for wcag aa, it would be great if the colors were high contrast out of the box.

**Comment by jenniferthibault** [comment]
Hi @lauraGgit ! Could you drop in some examples of what & where you're seeing?

**Comment by cmajel** [comment]
@lauraGgit going through the backlog and wanted to see if this is still an issue. Do you have examples where the contrast wasn't meeting WCAG AA?
