### ISSUE TITLE
Slide template suitability for projector presentations

### ISSUE THREAD

**Issue by ecayer** [18F/brand#139]
A lot of the slides have very small text.

I was advised years ago, and I've found it a useful guideline, that for presentations on a projector, 20pt is the smallest you can go without losing legibility. 

In this template, lots of the attractive slide designs, which I love because they save us from evil bullet points, also have very small text. I've felt inhibited from using these for anything which might ever be projected. Or I end up resizing and reformatting text on the slides, so they are decidedly less attractive than how it was designed.

I would love for a refreshed or extended template to have more slide options which take projected presentations into account!

**Comment by cmajel** [comment]
This came up again during the team coffee as a pain point, moving to the backlog for future sprints.

**Comment by cmajel** [comment]
@margaretmildrew would you be interested in doing some research on the font sizes used for different styles of presentations? I'm looking for specific guidance on what is most readable for different screen sizes (particularly stage presentations)

**Comment by margaretmildrew** [comment]
@cmajel I can definitely do that!

**Comment by cmajel** [comment]
@margaretmildrew welcome back! 🎉 do you have time to pick this back up?

**Comment by margaretmildrew** [comment]
Thank you!! Glad to be back online! @cmajel I can definitely continue looking into this! I'm slightly stretched on time right now since we're going into midterms at school, and I have a project from the TTS Outreach director due toward the end of October-- do you have a deadline in mind that I should have this research pulled together for you?

**Comment by cmajel** [comment]
@margaretmildrew there isn't a deadline, but do you think you could get us a few resources by the end of the month?

**Comment by margaretmildrew** [comment]
@cmajel Attached is a document with my research on this topic- I've included source links. Looks like the average suggested font size is 24pt. 
https://docs.google.com/document/d/1126pdkaMjZ9IShNC8a_z25qUQt-ZcF7GqVMgOEgKSyE/edit

**Comment by cmajel** [comment]
@margaretmildrew thanks for all this great work! We're hoping to pick this back up again soon. I've started a playground to experiment with different a min size of 22/24px and how it would affect common layouts.

https://docs.google.com/presentation/d/1de8F-_9TUpVnYSDR9azA1-CZKSZkbVfmiWpVfWoSwJY/edit#slide=id.g7665cf2900_0_5

**Comment by cmajel** [comment]
Per convo with @igorkorenfeld. Some possible paths forward:

* Guidance slide on how to adjust by presentation context
* Demo layout with scaled up text 
* Promoting guidance in other places (like Project resources, pinned in channels, identity site, others?)

**Comment by igorkorenfeld** [comment]
[This deck](https://docs.google.com/presentation/d/1KSJumypkPv10qrDQNdneo7UTfvL9qt1naal3IBA07vQ/edit#slide=id.g9cd2eb7c2b_0_19) is organized by suitability for projectors or not, let's revisit when in-person meetings start happening again.
