### ISSUE TITLE
2 columns icons master

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/brand#142]
The "2 columns icons" master slides have 4 dots, which I believe (based on the title of the master as well as the design) should be assigned icons when used. However, I don't think that is made clear, so many people use it with 4 big dots, which ends up looking a bit strange. I've also found that those dots are a bit smaller than I'd like once I add an icon.

**Comment by cmajel** [comment]
Reviewing this as we plan for the next few weeks.

We'll take a look at this once the new icons are in place and adjust as needed.

**Comment by cmajel** [comment]
A note that we're still planning on reviewing this once the new icons are available, and will think about how to create a demo slide showing how this can be used effectively.

**Comment by igorkorenfeld** [comment]
Add a demo to the template to show how to use icons in the blue dots
