### ISSUE TITLE
Smite Picons from 18F templates and styles, and replace it with a new icon set

### ISSUE THREAD

**Issue by jenniferthibault** [18F/brand#143]
A long time ago, when we were first getting started, very few people "designed" things for 18F's communication materials. That's since changed, and our approach is to empower everyone to be makers if we can provide loose guidance and templates they can follow. 

An icon set called [Picons](https://picons.me/) was chosen because it's narrow outlines worked well to balance our bold and heavier visual styles. At the time, it was super hard to find open source icons sets that weren't chunky solid styles. Picons came with constraints we could work with at the time: a reasonable fee for licensing, a specific number of licences, and a wide set of icon options.
We knew about the clause for a limited number of icons per project that was distributed, and that was ok for the time.

Later, as we developed templates that were more usable and shareable, more folks needed to access different icons for their work, and the restricted numeber of licenses felt out of line with our collaborative practices. Additionally, as more project teams wanted to build and disseminate leave-behinds using the 18F style, we ran up against the limit of icons we could put in a GitHub repo per project. We were able to provide clear guidance to our team member for 🔒 [how to use Picons within these constraints](https://docs.google.com/document/d/1AXruGbOQbVmQ2gyp0alMY_YCGt-2RQXCnOlJm9RcBuw/edit) but it still feels restrictive and limiting.

Now that more people at 18F need to access to an icon set for their work, and there's more icons sets to choose from under creative commons or open source licensing out in the world. I saw let's make the switch!

This task is competed when
- [ ] We've identified a replacement set of icons that:
   - [ ] works with 18F's visual identity styles
   - [ ] has a license that allows editing and distribution
- [ ] The icon set is replaced in our Slide deck template
- [ ] Guidance for finding and using the icon set is available from the [18F visual identity site](https://brand.18f.gov/)
- [ ] Follow-up issues have been made for replacing highly visible examples of Picons with new icons on 18F's assets, like the 18F site

**Comment by cmajel** [comment]
Goal for this sprint:
* @Dahianna audits 18F site for what Picons are in use
* @cmajel compares our slide set and 18F set against other open source icon libraries

**Comment by Dahianna** [comment]
Here's the audit: https://docs.google.com/document/d/1KFjwFDepULOxTHE_J7YqXWe7_DZ12A4wTOo_43Xrdzk/edit#heading=h.tx3xaxhckb93

**Comment by cmajel** [comment]
This has been updated with the new feather icon set 🎉 

https://brand.18f.gov/icons/
