### ISSUE TITLE
Provide a persona slide template

### ISSUE THREAD

**Issue by cmajel** [18F/brand#148]
I've come across a number of presentations where we are describing user personas, but these are often created as one-off, custom slide layouts. Since this is a common use case, we should recommend a template that will meet most needs.

- [ ] Audit past presentations and find patterns
- [ ] Develop a proposed layout
- [ ] Get feedback
- [ ] Add to official slide template

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
