### ISSUE TITLE
Written reports template

### ISSUE THREAD

**Issue by Dahianna** [18F/brand#160]
Currently there's a general Path Analysis report https://docs.google.com/document/d/1DBgwnnHuvR2fAojOwjP8gZ3_jA9pEAGRRKOnmH69d0s/edit but do we need one a more general one, like an 18F letterhead.

Look at the different report templates and decide on an official template

**Comment by Dahianna** [comment]
These are the templates available. Which one should we keep?

- [Basic doc template from brand site](https://docs.google.com/document/d/1lJBCZwgQzKsX5ggr7ykUaeuAUNqKsthENYCXMTA5Tbs/edit)

- [GSA template library doc](https://docs.google.com/document/d/1nqcQZPkVdLNWxaIzNB0_OOnFkpt3I7Q_Wt5w5bFYWOE/edit)

**Comment by cmajel** [comment]
Recapping our convo:
* It appears that the basic doc template is the most up to date version
* Next steps are to update the GSA repo

**Comment by Dahianna** [comment]
Added the template to the library, but I was unable to remove the old one. https://docs.google.com/document/u/0/?ftv=1&folder=0AIfvZ1MzHNScUk9PVA&tgif=d

I'll look to see who can do it for me

**Comment by Dahianna** [comment]
Talked to OSC and they didn't know. I'll reach out to GSA IT
