### ISSUE TITLE
 Find the current home of the 18F guides template and its maintainer

### ISSUE THREAD

**Issue by cmajel** [18F/brand#161]
Find the current home of the 18F guides template and its maintainer
Candidates include:

https://github.com/18F/guides
https://github.com/18F/guides-template
https://federalist-proxy.app.cloud.gov/site/18f/ux-guide/

**Comment by Dahianna** [comment]
https://agile.18f.gov/ - Porta
https://pages.18f.gov/content-guide - Content guild
https://content-guide.18f.gov/ - Content guild
https://agile-bpa.18f.gov/ - Edwin
https://agile-labor-categories.18f.gov/ -Edwin
https://acqstack-journeymap.18f.gov/ - Edwin?
https://accessibility.18f.gov/ - accessibility guild
https://methods.18f.gov/ - Julia
https://frontend.18f.gov/ - Heather
https://product-guide.18f.gov/ - Product

**Comment by cmajel** [comment]
I was able to get DAP set up so that I could look at traffic for the last month on these domains, and I found a few additional ones to consider:
<img width="405" alt="Screen Shot 2019-04-17 at 10 56 31 AM" src="https://user-images.githubusercontent.com/2374206/56298086-896c1680-60ff-11e9-94cf-652ac0aea353.png">

My notes on traffic and which guides are based on which template are in this spreadsheet and linked mural:
https://docs.google.com/spreadsheets/d/1DOsLCXFkKu5Vl8iUcGtK6l5w94FF10jQSbYHBEF_79s/edit#gid=0

**Comment by cmajel** [comment]
@Dahianna will be helping with this next sprint while I am out.

**Comment by Dahianna** [comment]
Updates on Mural.ly

**Comment by cmajel** [comment]
We are stepping back from this to pick up a few highly requested items, but will pick it back up again. 

A summary of what we found:
* With the help of @coreycaitlin, we've updated a mural (18F documentation venn diagram) showing:
  * What guides currently exist
  * Who owns them
  * Which front-end guide template they are using, which mainly consists of:
    * https://github.com/18F/uswds-jekyll
    * https://github.com/18F/guides-template
    * https://github.com/18F/guides-style

**Comment by cmajel** [comment]
Closing for now as initial research.

**Comment by cmajel** [comment]
@cmajel to add link to research mural

**Comment by cmajel** [comment]
https://app.mural.co/t/gsa6/m/gsa6/1548183070762/28155421d8846968ee1c8f5917e73a866bd1787f
