### ISSUE TITLE
Define what is an 18F "guide"

### ISSUE THREAD

**Issue by cmajel** [18F/brand#162]
There are a number of 18F guides in existence with divergent styles.

Examples:

https://18f.gsa.gov/guides/
https://eng-hiring.18f.gov
https://before-you-ship.18f.gov/
https://federalist-proxy.app.cloud.gov/site/18f/ux-guide/
One upcoming project where an 18F guide template would be used is for an open-source Guide to Hiring.

**Comment by igorkorenfeld** [comment]
As discussed with the [infrastructure group](https://github.com/18F/tts-tech-portfolio/issues/419#issuecomment-607451905), all templates should be moving to use uswds-jekyll. In the future they may also be transitioned to use a more hands-off theme: https://github.com/18F/isildurs-bane
