### ISSUE TITLE
Revisit subtitle for slide deck

### ISSUE THREAD

**Issue by cmajel** [18F/brand#163]
I see a lot of folks modifying the slide deck to include slightly larger subheads on slides to make them easier to read, such as this:

<img width="850" alt="Screen Shot 2019-04-08 at 10 55 10 AM" src="https://user-images.githubusercontent.com/2374206/55734007-cdb73280-59ec-11e9-8c14-5675f70eb728.png">

<img width="851" alt="Screen Shot 2019-04-08 at 10 56 13 AM" src="https://user-images.githubusercontent.com/2374206/55734209-27b7f800-59ed-11e9-861c-5188eb30d89b.png">

Here is the current formatting
<img width="801" alt="Screen Shot 2019-04-08 at 10 57 19 AM" src="https://user-images.githubusercontent.com/2374206/55734189-1f5fbd00-59ed-11e9-9b5b-3b2e696f1d4c.png">

**Comment by cmajel** [comment]
@Dahianna is going to look into our current formatting after the deck updates.

**Comment by Dahianna** [comment]
I changed the font of the preheader to Helvetica so they are on brand. In this deck, on slides 22 and 23, you can see examples of bold vs normal. https://docs.google.com/presentation/d/1Y3wj1B-70gz3s8BD1KTBjCToiBRZC-MpdrMSu8R2PjM/edit#slide=id.g5ecdbbee9e_0_123
