### ISSUE TITLE
Create a 1-col with preheader template

### ISSUE THREAD

**Issue by cmajel** [18F/brand#172]
We only provide preheaders for multi-column layouts, even though we see folks using the one-column layout frequently.

We should add a version with a preheader, title and single column text box, similar to how we have a title + single column text box. 

<img width="284" alt="Screen Shot 2019-07-03 at 11 31 09 AM" src="https://user-images.githubusercontent.com/2374206/60604634-14b38a80-9d86-11e9-8ced-679d2a5e06f7.png">

**Comment by cmajel** [comment]
@Dahianna per our conversation today, here is what I was thinking for this template:
https://docs.google.com/presentation/d/1f2RAKUUmRRtg_fMZGw_Oy1oZzqPQUEIkucBPNK1bnis/edit?usp=sharing

The headings would need to be adjusted to your new preheader values. If this looks good, let's wrap it into the alignment updates in #140 

## Preview
<img width="839" alt="Screen Shot 2019-07-03 at 12 51 54 PM" src="https://user-images.githubusercontent.com/2374206/60610248-644b8380-9d91-11e9-83b1-37f108864fc8.png">
<img width="846" alt="Screen Shot 2019-07-03 at 12 51 59 PM" src="https://user-images.githubusercontent.com/2374206/60610249-644b8380-9d91-11e9-956a-08d576002d87.png">

**Comment by Dahianna** [comment]
Ok, the slides on the link look blank to me, so I've asked for edit access.

**Comment by Dahianna** [comment]
@cmajel Ok, I added them to the in progress deck: https://docs.google.com/presentation/d/1jBVvqOLrB2NCJR2J_gEspTToeGeAma0DK-jtoocDLzg/edit#slide=id.g5ca780073e_2_706
If you don't have any changes, I'm ready to merge to the master deck

**Comment by cmajel** [comment]
@Dahianna styling-wise this looks good. I added bullets to the demo slide since that is seems to be the most common use case:
<img width="765" alt="Screen Shot 2019-07-10 at 9 14 38 AM" src="https://user-images.githubusercontent.com/2374206/60971917-2c918e00-a2f3-11e9-8927-e727d072e649.png">

However, I am seeing on the demo deck that these changes are on the slides, not the master layout. And, for example, I can't do something like `insert a 1col with preheader` slide from this menu. 
<img width="741" alt="Screen Shot 2019-07-10 at 9 12 53 AM" src="https://user-images.githubusercontent.com/2374206/60972003-65c9fe00-a2f3-11e9-9432-b52a9c95a2be.png">

Is updating the master the next step?

**Comment by Dahianna** [comment]
I just did updated master. Let me know if it works now
