### ISSUE TITLE
Add a link to the 18F letterhead template on brand.18f.gov

### ISSUE THREAD

**Issue by cmajel** [18F/brand#173]
We have a letterhead template that was recently requested and updated by @austinhernandez 
 to include the black 18F logo.
https://docs.google.com/document/d/16rQOcP9XYu4qlPwrswTXKO7XBKegxejvXocxo98rW5c/edit

This should be added to the https://brand.18f.gov/templates/ so that it is easier to find and discoverable to 18Fers. 

Information that would be helpful to include:
* When to use the template and when not to
* Instructions for use

**Comment by Dahianna** [comment]
Links are up to date

**Comment by cmajel** [comment]
updates from @Dahianna 
- Updated font
- added GSA logo

Will be reviewing with Corey before merging in.

**Comment by Dahianna** [comment]
Pull request merged.
