### ISSUE TITLE
Include older members of the public in your default avatars set

### ISSUE THREAD

**Issue by pburkholder** [18F/brand#175]
A few folks with wrinkles and grey hair would be a terrific addition to https://docs.google.com/presentation/d/1CXXvxBbVjO3LjIUwRYEbk8WHpsG0AJdUc6SI_jAZDNQ/edit#slide=id.g5f21c1523a_0_6

Thanks, Peter

**Comment by annepetersen** [comment]
Agreed! I was asking for folks with reading glasses, but I'm not sure if that got added to the Sketch base, much less here.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
