### ISSUE TITLE
Styleguide updates

### ISSUE THREAD

**Issue by Dahianna** [18F/brand#177]
Now that we changed the design for the blog template we need to update the blog post template in the guide.

- [ ] Documentation should include gotchas when relevant. Make sure that we fully document all the components that someone needs to make something work
- [ ] Consider allowing accordions to both expand at the same time
- [ ] Accordions should go full width, but have constrained content
- [ ] Could include simple and complex examples of how code is generated. Think project cards. The simple include is great, but the html example is also useful
- [ ] Add instructions and guidelines for project images
- [ ] Update the [guide](https://18f.gsa.gov/styleguide/layouts/#blog-post-template)

**Comment by Dahianna** [comment]
So, I looked back at the original issue in the 18F-site repo and it was created by someone who left 18F. I checked the guide and it seems to be up to date to me.

**Comment by Dahianna** [comment]
- code for [sidebar](https://18f.gsa.gov/styleguide/layouts/#sidebar) doesn't populate
- code for [blog tags](https://18f.gsa.gov/styleguide/blog-components/#blog-tags) doesn't populate
- It seems example need to be reviewed for [blockquotes](https://18f.gsa.gov/styleguide/blog-components/#blockquotes)
- Consider removing team photo section and adding [images](https://18f.gsa.gov/styleguide/blog-components/#images) for project pages

**Comment by cmajel** [comment]
Per chat, we could try using this include that works on other parts of the guide, and see if it fills in the code accordion.

```
{% include details-code.html title='testimonial' content=testimonial_codeblock lang="html" description=testimonial_description %}
```

**Comment by cmajel** [comment]
I can look at this and see if I can figure out why this fix isn't working. Otherwise, we may need a dev consult.

**Comment by cmajel** [comment]
Alright, I looked into the missing code blocks and I have a theory. Putting my notes here while I continue to investigate.

It appears that the code block do have content inside, but sometimes the `div` wrapping the codeblock's content is missing a `aria-hidden="false"` flag that actually allows it to be displayed. 

### Sidebar example, where there isno flag
<img width="1429" alt="codeblock-no-flag--sidebar" src="https://user-images.githubusercontent.com/2374206/68957305-c54f8300-0797-11ea-9106-8087fc81d691.png">

### Breadcrumb example, where is there is a flag
<img width="1439" alt="codeblock-with-flag--breadcrumb" src="https://user-images.githubusercontent.com/2374206/68957314-c84a7380-0797-11ea-8a01-6701f66c0f6b.png">
When I manually add the flag to the sidebar (and other code components where the code block doesn't open), it appears.

I'm not sure why the flag appears on some blocks and not others. But, I can take another look next week. Or, @Dahianna if there is a dev helping with the 18F site, they may be able to give a faster answer.

**Comment by cmajel** [comment]
Adding a note that I _believe_ the base code for this accordion component comes from `details-code.html` and that the div is populated here in lines 22-24. However, I don't see an obvious way for a  `aria-hidden="false"` flag to be applied to the div on line 22. 

<img width="1009" alt="Screen Shot 2019-12-03 at 5 15 34 PM" src="https://user-images.githubusercontent.com/2374206/70094453-8a9b7680-15f0-11ea-983a-a5f5bcabbb56.png">

**Comment by adunkman** [comment]
Looks like there’s an ID collision happening preventing the accordion from functioning properly. 

![image](https://user-images.githubusercontent.com/14930/70154641-db59b080-167e-11ea-8540-587b13e7d2b6.png)

The `aria-hidden` flags are added by JavaScript, and the JavaScript is finding `h3#sidebar` rather than `div#sidebar` as intended. 

This is a collision between auto-generated IDs for the heading and auto-generated IDs for the accordion. A quick, easy, and perhaps right fix would be to change `details-code.html` to add a suffix to its IDs so it generates something different — perhaps `{{ include.title | slugify }}-accordion`?

**Comment by cmajel** [comment]
@cmajel to take a look and see if this branch is possibly out of date and causing the issue. If not, ping eddie again on the build error.
