### ISSUE TITLE
18F Google Slide template missing

### ISSUE THREAD

**Issue by ivandj** [18F/brand#178]
Issue:
Missing 18F Google Slide Template on Google Slide Template site.

How to reproduce the issue:
1/ Open the page: https://brand.18f.gov/templates/
2/ Navigate to "GSA slide template gallery" button
3/ Click on the button which will take you to: https://docs.google.com/presentation/u/0/?ftv=1&folder=0BwWYNZcEDfwabE13dnZpbFN5QmM&tgif=d
4/ try to follow the instructions mentioned on the page:
```
To make a new Google Slides presentation
In Google Drive, click New > Google Slides > From a template.
Once the GSA Template Gallery opens, choose the 18F Slide Theme_MASTER presentation from the list.
This will create a copy of the template. Rename your presentation so that the team doesn't confuse it with the original.
```

5/ Cannot find 18F Slide Theme_MASTER on the google page.

**Comment by cmajel** [comment]
@ivandj thank you for your comment - the 18F deck is for TTS employees, so outside folks are not able to access it.
