### ISSUE TITLE
Who is currently working on a guide?

### ISSUE THREAD

**Issue by cmajel** [18F/brand#191]
These may be possible partners / folks to work with as we revisit the guide template.

Possible candidates:
UX guide
Hiring guides?

**Comment by cmajel** [comment]
Sounds like UX guide may be a good candidate to work with on a guide template. Content is currently in review.

**Comment by Dahianna** [comment]
UX guide: Melissa Braxton
https://docs.google.com/document/d/1I7skYkn74Inz9NRFvEkcpT6L_WBFtvD22q5i3yGgxF8/edit

**Comment by cmajel** [comment]
Mural of known guides and what templates they are using:
https://app.mural.co/t/gsa6/m/gsa6/1548183070762/28155421d8846968ee1c8f5917e73a866bd1787f

**Comment by cmajel** [comment]
TTS public sites and pages:
https://docs.google.com/spreadsheets/d/1xavc-xZ-7TQRsGGvpg-Cr0PbQwaRgIF6wiKGfGIA7uU/edit#gid=0
