### ISSUE TITLE
Tag icon color in Feather set

### ISSUE THREAD

**Issue by schnuerle** [18F/brand#192]
The Tag.png icon in the [Feather Icon Set](https://github.com/18F/brand/blob/master/assets/dist/18F_feather.zip) in the png/svg folders white/medium/blue is black in each instead of the appropriate color.  It is correct in the top-hits sub folders.

I'd replace them and rezip it myself but I'm not sure how you want the zip contents exactly.  And it has the __MACOSX hidden folder and .DS_Store files which I wasn't sure was intentional.

So, so minor of an issue, but wanted to point it out.  Thanks so much for this icon set!

**Comment by cmajel** [comment]
@schnuerle thanks for letting us know - I see the issue too. We'll work on getting that updated.

**Comment by cmajel** [comment]
@schnuerle thanks for letting us know about this issue! We fixed this in our last release.
