### ISSUE TITLE
Recruiting info cards check-in with talent

### ISSUE THREAD

**Issue by Dahianna** [18F/brand#199]
Check with Talent to ensure the current recruiting card meet their needs. Once it's been approved by talent we can share it with the team.

**Comment by cmajel** [comment]
There is interest in having an updated version of this for the CFA summit.

* Update the email
* OPP > Solutions

Files here:
https://github.com/18F/design-lab/issues/27

**Comment by cmajel** [comment]
@Dahianna I updated these cards and rebuilt them in InDesign so that we can easily edit them in the future. Can you check them for language?

[TTSbusinesscard--Winter2020.zip](https://github.com/18F/brand/files/4231468/TTSbusinesscard--Winter2020.zip)

**Comment by Dahianna** [comment]
Thank you!
