### ISSUE TITLE
Why we work in government redux

### ISSUE THREAD

**Issue by Dahianna** [18F/brand#200]
Create an updated version of the [Why did you join 18F](https://18f.gsa.gov/2016/03/21/we-asked-100-of-our-coworkers-why-did-you-join-18f/) and [a day in the life](https://18f.gsa.gov/search/?q=a+day+in+the+life) posts

**Comment by cmajel** [comment]
From planning:
* [Public service recognition week](https://psrw.ourpublicservice.org/) is in May, perhaps we could organize posts around that time. 
* Also, would want to talk to talent about the kinds of questions they're getting from candidates so that this post could help answer these questions.
