### ISSUE TITLE
Design iteration case studies

### ISSUE THREAD

**Issue by cmajel** [18F/brand#205]
To show what the design iteration process looks like on the ground

Initial Ideas
https://docs.google.com/presentation/d/10PGVBaxlMahv0lA5rrfh8RnAxgQ3AabOigpF4bkzGfk/edit#slide=id.g6d6daf6285_0_0

**Comment by cmajel** [comment]
Work on having updates for design outreach meeting on 3/10

**Comment by cmajel** [comment]
Work on having updates for design outreach meeting on 3/10

**Comment by igorkorenfeld** [comment]
We will revisit this, clean up the deck, and get feedback from product design team. Eventual home may be the [project resources drive](https://drive.google.com/drive/folders/1L9qqS6-b-emvlWJ4JPCG58LW62bbV361)

**Comment by cmajel** [comment]
Picking this back up and starting to fill in more examples and framing. [WIP deck here](https://docs.google.com/presentation/d/10PGVBaxlMahv0lA5rrfh8RnAxgQ3AabOigpF4bkzGfk/edit#slide=id.gaede2c7990_0_90).
