### ISSUE TITLE
Update "If you work at another organization" section

### ISSUE THREAD

**Issue by cmajel** [18F/brand#210]
On the [homepage of the brand site](https://brand.18f.gov/). Add a note about attribution for graphics.

* If you use our graphics, please let folks know where you found them.
* Include an attribution example.

**Comment by Dahianna** [comment]
Started [this PR,](https://github.com/18F/brand/pull/233) just needs example.

**Comment by igorkorenfeld** [comment]
@cmajel to add example to the PR

**Comment by Dahianna** [comment]
Closed by https://github.com/18F/brand/pull/233
