### ISSUE TITLE
Include color combination table to master deck

### ISSUE THREAD

**Issue by Dahianna** [18F/brand#215]
Create a slide with the table[ in the brand site](https://brand.18f.gov/color-palette/
).

**Comment by cmajel** [comment]
@Dahianna @igorkorenfeld ready for your review

[Demo slide in this deck](https://docs.google.com/presentation/d/1Y7RfPNXPzKQmmurjksdOV46EyR5SVLgNnXFkQi-E1Uw/edit#slide=id.g8fe1620182_0_0)

Screenshot:
<img width="858" alt="Screen Shot 2020-08-12 at 3 49 42 PM" src="https://user-images.githubusercontent.com/2374206/90061049-97aa5280-dcb3-11ea-9a92-9cfd22354732.png">

**Comment by igorkorenfeld** [comment]
Nice! The only suggestion I have is to move the textbox (and possibly the the slide title) up a bit, so that it's not so tight at the bottom edge of the slide. The table, additional links, and guidance on visual shift are all great.

**Comment by Dahianna** [comment]
Christine will finish edits and send to Dahianna to add to master template

**Comment by cmajel** [comment]
@Dahianna this is ready for your review and to be added to the main template! [Here's my working deck (slide 4).](https://docs.google.com/presentation/d/1Y7RfPNXPzKQmmurjksdOV46EyR5SVLgNnXFkQi-E1Uw/edit#slide=id.g8fe1620182_0_0)

**Comment by Dahianna** [comment]
Done! Added color slide to master deck
