### ISSUE TITLE
Fix padding on slides

### ISSUE THREAD

**Issue by Dahianna** [18F/brand#216]
Reduce the amount of padding between text boxes

**Comment by Dahianna** [comment]
Will send to Christine and Dahianna for review

**Comment by igorkorenfeld** [comment]
Read for your review: https://docs.google.com/presentation/d/1pLP6EZ-YVvrwMCs7JsWdoYoS-6QOedQqM8GWBlw-q3s/edit?usp=sharing

Slides 15-17 have the blue bar above the title. I am thinking that slides with a pre-header/eyebrow title will not have the blue bar, because it competes with the eyebrow.

**Comment by cmajel** [comment]
* Decoupling this with the eyebrow work, since that might take longer
* Shared at product design huddle for feedback (eyebrow and padding). Generally positive feedback for padding. 
* granted @igorkorenfeld edit rights to the master template in the library
