### ISSUE TITLE
Icon guidance for 18F guides page

### ISSUE THREAD

**Issue by cmajel** [18F/brand#224]
* Recommendations for UX guide and Agile Budgeting
* What icons are being used now and are there feather options?

https://18f.gsa.gov/guides/

Check in with @jstrothman

**Comment by jstrothman** [comment]
@cmajel I added a review request for the [18F site Guides page pull request](https://github.com/18F/18f.gsa.gov/pull/3217) where I'm adding the UX Guide to see if the Feather icon I chose is ok for now, until you've had a chance to review further as part of this issue

**Comment by igorkorenfeld** [comment]
For future reference, icons can be found on the [brand site](https://brand.18f.gov/icons/)
