### ISSUE TITLE
Update typo on footer

### ISSUE THREAD

**Issue by Dahianna** [18F/brand#226]
Update the template, 18F site and let team know of changes

**Comment by igorkorenfeld** [comment]
"Accessibility" is misspelled in the "learn more" menu  
![image](https://user-images.githubusercontent.com/52677065/90660402-db510f00-e213-11ea-9097-f562d27c7fc7.png)

**Comment by cmajel** [comment]
@igorkorenfeld [fixed on the federalist port](https://github.com/18F/federalist-jekyll-uswds-18f-port/commit/1279908e6bac55173c4ba49233cceaa2d187ea94).

**Comment by igorkorenfeld** [comment]
Nice, I know @Dahianna fixed on the 18F site, Nick edited it on the UX guide, I adjusted it on the De-risking guide, and just submitted a PR for the Content guide. I think that covers it?

**Comment by Dahianna** [comment]
All done!
