### ISSUE TITLE
Different padding on text boxes on a template slide

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/brand#235]
In the 18F Slides template on the "2 columns icons light" slide, I noticed that the padding on the text boxes in the left column is different than the padding in the right column. On the right, it is set to 0 inches; on the left, it is set to 0.1 inches. The result is that the left and right text is not aligned. See screenshots for further illustration! 

![Screen Shot 2020-10-26 at 3 51 12 PM](https://user-images.githubusercontent.com/42982184/97221350-23a42480-17a3-11eb-8477-39a3a24fdd65.png)
![Screen Shot 2020-10-26 at 3 51 21 PM](https://user-images.githubusercontent.com/42982184/97221356-243cbb00-17a3-11eb-9fb9-54fef18dbde1.png)

Should be an easy fix, but I didn't want to mess with the slide template, since I know there has been some investigation into how to make sure there is only one version floating around.

**Comment by igorkorenfeld** [comment]
Thanks for pointing this out @juliaklindpaintner! Should be fixed now, let me know how it looks to you

**Comment by juliaklindpaintner** [comment]
Looks good to me! Thanks!
