### ISSUE TITLE
Add footer identifier to the site 

### ISSUE THREAD

**Issue by cmajel** [18F/brand#246]
From our 12/8 sync

We'll need to add the GSA identifier to the site, similar to what we did on [the UX guide](https://ux-guide.18f.gov/). It's possible we'll need to build a custom layout to accomplish this. 

Example of UX guide footer identifier:
![Screen Shot 2020-12-08 at 2 18 51 PM](https://user-images.githubusercontent.com/2374206/101530813-63dcf200-3960-11eb-92ed-c365813167bc.png)

**Comment by igorkorenfeld** [comment]
We may need to use the new [USWDS version](https://designsystem.digital.gov/components/identifier/) of it, though we may want to modify the background color to be our brand color.

![image](https://user-images.githubusercontent.com/52677065/101532646-b232c680-3949-11eb-9b5a-88dd73ebcc32.png)
