### ISSUE TITLE
merge into the Handbook?

### ISSUE THREAD

**Issue by afeld** [18F/brand#248]
A lot of similar employee guidance exists in the Handbook; is there benefit to having a standalone microsite for branding? Otherwise, it's one more site to keep dependencies up to date, comply with IDEA Act, etc.

**Comment by cmajel** [comment]
Thanks @afeld - we chatted about this at our coworking, and believe this should remain as its own site. Here's our reasoning:

* We don't really see much duplication from the handbook - most of whats on https://brand.18f.gov/ is unique. For examples, details on our font stack, color combinations, and where to access various assets.
* There's a decent amount of content, and also diagrams, like the [accessible color combos matrix](https://brand.18f.gov/color-palette/) would be difficult to replicate in HTML on the handbook. 
* Definitely hear you on the maintenance piece. We're close to relaunching this with the `uswds-jekyll` framework to help streamline maintenance. We've also been able to keep up a team to work on identity assets and maintenance, even as other contributors term out.

I'll close this for now, but feel free to reopen for additional discussion.
