### ISSUE TITLE
Visited links in footer are hard to read

### ISSUE THREAD

**Issue by jstrothman** [18F/brand#258]
Visited footer links appear as #046b99 on #1C304A, making them inaccessible.
<img width="1423" alt="Screen Shot 2021-02-27 at 11 26 12 AM" src="https://user-images.githubusercontent.com/1080991/109503646-861a7380-7a68-11eb-9f62-93af76b30989.png">

**Comment by christophermather** [comment]
Resolved via Guides consolidation and template updates.
