### ISSUE TITLE
Portfolios Site Font

### ISSUE THREAD

**Issue by Dahianna** [18F/brand#272]
Font needs to be updated to Helvetica instead of public sans

**Comment by Dahianna** [comment]
Issue was created in the [Portfolio repo](https://github.com/18F/portfolios/issues/47)

**Comment by Dahianna** [comment]
Dahianna will share issue on Slack channel to start discussion

**Comment by Dahianna** [comment]
@igorkorenfeld will clone site and make font change to see how it would look

**Comment by igorkorenfeld** [comment]
Opened a [PR](https://github.com/18F/portfolios/pull/54) to update the fonts
