### ISSUE TITLE
Broken link to "our core values" on the home page

### ISSUE THREAD

**Issue by cannandev** [18F/brand#284]
**What's wrong?**

There's a broken link on the homepage. https://brand.18f.gov/#if-you-work-at-18f
The "our core values" link goes to https://handbook.tts.gsa.gov/history-and-values/#our-values - that page doesn't exist, so we land on a 404 page. Below are a couple of screen shots:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/381122/185514033-0fe4d886-ad1f-4ccd-a444-1ae8b6a22e4b.png">

<img width="885" alt="image" src="https://user-images.githubusercontent.com/381122/185514428-2954f145-b838-46f2-8763-37e69327321e.png">

**How to fix it?** 

Not sure if the intent was to link to 18F core values or TTS 🤷🏾. But it should go somewhere.

**Comment by igorkorenfeld** [comment]
Noting to self  that the URL changed to: 

https://handbook.tts.gsa.gov/about-us/tts-history/#our-values

**Comment by geekygirlsarah** [comment]
Oh, I saw this wasn't fixed but missed it was assigned to @igorkorenfeld. If I overstepped, I'm sorry! Figured it was a quick fix I could do since I saw the corrected link.

**Comment by igorkorenfeld** [comment]
No worries, thanks for making the fix and PR :) 

I'll review it either at the end of today or Monday.
