### ISSUE TITLE
Please create a Google Slides template

### ISSUE THREAD

**Issue by esgoodman** [18F/brand#32]
I'm hoping that this effort will produce a default Google Slides template. It's something that I find myself frequently needing -- and usually at the last minute, when I don't have time to make the styles myself. Don't know if this is the right place to ask but...

**Comment by ericronne** [comment]
It is the right place to ask! Now that we have a solid alpha of the branded keynote deck, we've already begun to noodle with the google slides version. Gaps in billable work permitting, we should have a conversion within two weeks. Please ping if you can think of any unique slide layouts not in the keynote which you'd like to have.

**Comment by esgoodman** [comment]
Super, will do.

**Comment by ericronne** [comment]
V1 done and done.
Instructions included in [this pdf] (https://pages-staging.18f.gov/brand/assets/dist/Using_18Fs_Templates.pdf).
