### ISSUE TITLE
See if favicon can be further refined

### ISSUE THREAD

**Issue by ericronne** [18F/brand#39]

**Comment by ericronne** [comment]
Perhaps we get creative and do a crop or something?
Let's brainstorm

**Comment by maya** [comment]
@ericronne is this resolved via #38?

**Comment by ericronne** [comment]
No. I feel that the new version is an improvement, but could be better. At the end of the day, it might be impossible to smoosh the full logo down to 16x16. So we might want to experiment with a more artistic interpretation. As time permits.

**Comment by ericronne** [comment]
@maya is there a way to test this favicon file i just created?
Somehow chrome (and other browsers?) seems to be using the 32x32 version, and squishing it down to 16x16. So i've made a version which has only the 16x16. thx!...

[favicon.ico.zip](https://github.com/18F/brand/files/87473/favicon.ico.zip)

**Comment by maya** [comment]
@ericronne We shouldn't add another zip, rather try to understand why the file is not displaying correctly. Does the favicon.ico file contain both 16x16 and 32x32?

As someone who has a retina screen, I definitely want the 32x32, so wouldn't want to remove that.

**Comment by ericronne** [comment]
Sorry what i wanted to do was temporarily test it as the favicon for the site itself, not include it in the downloads. The current .ico was created using both the 16 and 32 sizes, and chrome, for one, doesn't pull the 16. It fakes it. I used www.favicomatic.com to make it. Ping me for a hangout?

**Comment by jenniferthibault** [comment]
Closing until there's a need for this in the current org
