### ISSUE TITLE
Resolve licensing / public-repo question and document

### ISSUE THREAD

**Issue by ericronne** [18F/brand#44]

**Comment by jenniferthibault** [comment]
Here’s the repo checklist. https://pages.18f.gov/open-source-guide/github-repo-checklist/

It shows licensing as a bullet under the README, but no guidance on 18F options for licensing.

**Comment by ericronne** [comment]
thx

**Comment by ericronne** [comment]
Let's discuss how this impacts our blog post, too.

**Comment by jenniferthibault** [comment]
[Notes on this discussion](https://docs.google.com/document/d/1rnc4Lu9uW5amN6jnvuRB5Vln0he01hWeBdjKwJRPZ5Y/edit)
