### ISSUE TITLE
Update 18F tock logo

### ISSUE THREAD

**Issue by jenniferthibault** [18F/brand#48]
Submit a PR to the Tock repo with the updated 18F logo

**Comment by batemapf** [comment]
current file is at tock/tock/static/img/18f-logo.png

**Comment by jenniferthibault** [comment]
Not quite done—the new logo is there, but looks like someone used a low-res screencap. I'll fix this soon.

**Comment by batemapf** [comment]
hmm, i pulled the file right out of this repo. see file in the tock repo: https://github.com/18F/tock/tree/master/tock/tock/static/img.

**Comment by jenniferthibault** [comment]
Closed by https://github.com/18F/tock/pull/355

Thanks for your patience and help @batemapf !
