### ISSUE TITLE
Provide intro to 18F Brand site

### ISSUE THREAD

**Issue by amberwreed** [18F/brand#49]
Write a brief into to why we've developed a brand toolkit.

Please add notes here:
https://docs.google.com/document/d/1tNyhh_gY7Z4YhZeamaqMT3sQcYuKi4S_oJJ0qAfc6Qg/edit

**Comment by ericronne** [comment]
Awaiting approval from Hillary and Kate

**Comment by amberwreed** [comment]
1. Write intro with Kate 
2. Hillary approval
3. Maya to add to site

**Comment by ericronne** [comment]
Draft...
https://docs.google.com/a/gsa.gov/document/d/1tNyhh_gY7Z4YhZeamaqMT3sQcYuKi4S_oJJ0qAfc6Qg/edit?usp=sharing

**Comment by jenniferthibault** [comment]
FYI: Assigned this to myself for implementation.
