### ISSUE TITLE
Update instructions with latest pdf to include google template directions

### ISSUE THREAD

**Issue by amberwreed** [18F/brand#52]

**Comment by amberwreed** [comment]
[Using_18F's_Templates.pdf](https://github.com/18F/brand/files/87782/Using_18F.s_Templates.pdf)

**Comment by ericronne** [comment]
@maya Can you update the instructions file on the site with this new version? Note that the file name has changed, to be more general (added google).

**Comment by maya** [comment]
@ericronne done in 3470610.

I removed the apostrophe from the file name.
