### ISSUE TITLE
Bug: Expunge Droid Sans from keynote

### ISSUE THREAD

**Issue by ericronne** [18F/brand#54]

**Comment by ericronne** [comment]
I gave the template the once-over and couldn't find any droid sans, but i do get the error when i uninstall that font. I'm sure it's a hidden character, and would likely take a long time to ferret out. It may also be a keynote bug (cf https://discussions.apple.com/thread/5485262?tstart=0)

Since it doesn't impact the visuals, my vote is we close this.
Agree @rtwell @jenniferthibault @amberwreed?

**Comment by rtwell** [comment]
i wonder if a default text style (whilst unused) is triggering the error?

closing is ok w/me

**Comment by jenniferthibault** [comment]
My understanding is that closing an issues should equate to "we fixed it" or "action has been taken."

Since this bug is still existing, (and I think is the most common thing people come to the branding channel to report) I might suggest instead just moving this issue out of the current sprint and into the backlog, and keeping it open until it is indeed resolved.

**Comment by ericronne** [comment]
Ok, but it'll probably be a vestigial limb until apple fixes keynote

**Comment by ericronne** [comment]
or vestigial wart, i should say :P

**Comment by ericronne** [comment]
The bug seems to be hidden within the table which is on the Table master page. Deleting the table **usually** causes the warning to disappear. The font is nowhere to be found on the table, though. Even when reducing it down to a single cell, the warning still appears.

I recommend we redraw the table from scratch, which is tedious. I'll look into it.

**Comment by jenniferthibault** [comment]
Nice sleuthing!

**Comment by ericronne** [comment]
Collaborating with a citizen; a fellow Ronne, no less :)

**Comment by norphin** [comment]
Hi, yep the droid bug was in that table's master page, so I rebuilt it.

Found a few other tiny items, too.
Here's what changed: 

 - pg. 26 – deleted table in master page, rebuilt
 - pg. 28 – removed duplicate (larger) "We Are 18F!" type underneath blue box.
 - pg. 29 – removed duplicate contact/follow/work together type (two layers were on top of each other. 

[18F_Keynote_fixes_2016-08-10.zip](https://github.com/18F/brand/files/412118/18F_Keynote_fixes_2016-08-10.zip)

**Comment by ericronne** [comment]
Works for me!! TYVM!

Keynote seems to remember which slide you last viewed, so i clicked on slide 1 and re-saved. We will can address the **other** font issue (see #114) later.

If someone (or two) can confirm this bug fix, then we can create an issue to replace the files in the repo. Thx!

[18F_Keynote_fixes_2016-08-10.zip](https://github.com/18F/brand/files/412163/18F_Keynote_fixes_2016-08-10.zip)

**Comment by afeld** [comment]
No error for me! 👏 Still don't totally understand why the ZIP contains three files...are all of them needed? We should add a note in [the instructions](https://pages.18f.gov/brand/presentation-themes/), or just remove the not-needed files.

**Comment by ericronne** [comment]
"18F_Template_2016-08-10.key" is the template for users whose Keynote is up to date.
"keynote09_18F_Template_2016-08-10" is those using v9 of Keynote.
"18F_Template_2016-08-10.kth" is the theme which users can add to their Keynote theme gallery.

And yes, the instructions could be more clear on this matter!

I love the simplicity of the current instructions, though. Perhaps we could include a more detailed readme to include in the download. Thoughts, @jenniferthibault @rtwell @amberwreed?

**Comment by afeld** [comment]
Note that issue/suggestion is completely tangential!

**Comment by rtwell** [comment]
agreed, a little clarity in the readme would be useful—almost what mr.
ronne said verbatim. Something like:

There are 3 files included in the download:

*1) 18F_Template_2016-08-10.key* is the template for users whose Keynote is
up to date.

*2) keynote09_18F_Template_2016-**08-10* is those using Keynote v9.

*3)* *18F_Template_2016-08-10.kth* use this file to add the 18F theme to
the Keynote theme gallery.

**Comment by rtwell** [comment]
Keynote is currently version 6.6.2. v9 doesnt seem to make sense,
numerically. or is it just weird numbering by apple?

**Comment by ericronne** [comment]
Good catch, @rtwell!

Keynote used to be part of iWork; so "v9" refers to iWork v9. The keynote release in that package was v5, so perhaps we should rename the historical version of the template.

@afeld do you recommend a certain naming convention for all of the files (eg versioning them instead of including the release dates)?

**Comment by rtwell** [comment]
ah, i completely forgot about iWork. perhaps we should say something like
"works with iWork v9 or Keynote vX and older"?

whatever is clearest, imo

**Comment by jenniferthibault** [comment]
Hey @norphin - thank you so much for tacking that, it was such a headache.

I've been starting work on our [next stage issue](https://github.com/18F/brand/issues/113#issuecomment-242715567) which updates the whole file package to Helvetica Neue from Nimbus, and I'm hitting a similar bug. This time, I can't seem to find a lingering instance of Nimbus to smite. I'd love to know how you were able to target the remaining instance of Droid in the earlier file, what's your secret?

(All, I'll plan to integrate the explainers for the keynote file you've been talking about as part of that issue).

**Comment by norphin** [comment]
Hi @jenniferthibault 

I don't know if I have any tricks to target the error down, but this is pretty much the process I followed: 

- Save a copy.
- Delete half the pages, reopen.
- if you still get an error, delete the other half of the pages.
- Keep deleting half until you laser beam in until you find the one bad page.
- Then zero in on the individual items on the page, just deleting half the items and reopening until you don't get the error message. 

Sorry to hear you're getting that error, though. I'd be happy to check that out soon if it hasn't yet been fixed.

**Comment by jenniferthibault** [comment]
Thanks @norphin that's similar to what I tried to do too, but couldn't pinpoint it. And no apologies necessary! If it weren't for you, we'd be hunting **two** bugs, one for Droid and one for Nimbus Sans Bold! 

If you're up for taking a crack at it, we'd certainly appreciate it! If not, I think it's an acceptable known bug that shouldn't keep us from putting the file online and keeping progress going anyways. 

The new file is over in https://github.com/18F/brand/issues/113#issuecomment-242715567

I'm going to close this issue in favor of moving any more discussion into that issue.
