### ISSUE TITLE
Document Template (google)

### ISSUE THREAD

**Issue by amberwreed** [18F/brand#56]

**Comment by ericronne** [comment]
A WIP....
https://docs.google.com/a/gsa.gov/document/d/1OK60_6Rh_yKIt3gzODeSlMRaNndV5RQYMcns6scsVUU/edit?usp=sharing

**Comment by ericronne** [comment]
Looks like we can submit the template here...
https://drive.google.com/a/gsa.gov/createtemplate?referringview=domain

I'll try and see if that works. I don't know if you're able to submit a template on the new google docs.

**Comment by ericronne** [comment]
Test template...
https://drive.google.com/a/gsa.gov/templates?q=18f&sort=hottest&view=domain

**Comment by ericronne** [comment]
Picking this up again, stay tuned. Also leveraging some style work spec'd by @jenniferthibault in this [google template] (https://docs.google.com/a/gsa.gov/document/d/1My6fx4EiOu6mTlAhqlBw64nP8PUVs_mOAi1Ajjm_h1k/edit?usp=sharing)

**Comment by jenniferthibault** [comment]
We have this now! Closing
