### ISSUE TITLE
Add tumbnails of other desktop art to site

### ISSUE THREAD

**Issue by jenniferthibault** [18F/brand#58]
We currently have just one desktop image showing, which hides some of the really cool images we created. 

Today, a new team member was downloading the file and asked why it was such a large file for one image. When I said there were multiple images, it made more sense.

**Comment by jenniferthibault** [comment]
@rtwell also heard some user feedback around this: 
> desktop image download too big, don’t need all of the images, would rather choose which image they prefer from a thumbnail and download

**Comment by jenniferthibault** [comment]
More thoughts from the [slack channel](https://18f.slack.com/archives/18f-branding/p1453398358000110):

If we convert the desktop art to JPGs instead of PNG's, it would reduce the file size

**Comment by Dahianna** [comment]
Outdated
