### ISSUE TITLE
Use pages-staging.18f.gov?

### ISSUE THREAD

**Issue by mbland** [18F/brand#6]
@shawnbot If this is intended to be one of the [18F Guides](https://pages.18f.gov/guides/), might you consider using an `18f-pages-staging` branch to push to https://pages-staging.18f.gov/brand/ for development?

**Comment by maya** [comment]
@mbland this is not meant to be an 18F guide, it's going to be a styleguide for the 18F brand. Do you still  think we should push to `18f-pages-staging`?

**Comment by mbland** [comment]
You certainly could, of course. You don't have to use the 18F Guides style to publish to 18F Pages.

**Comment by maya** [comment]
This is complete. The site displays here: https://pages-staging.18f.gov/brand/

**Comment by mbland** [comment]
Oh, I should've mentioned: If you push to `18f-pages-internal`, it'll show up at https://pages-internal.18f.gov/brand/. It the exact same auth as pages-staging, but the host name signals a different intent, if you want that.
