### ISSUE TITLE
font for code?

### ISSUE THREAD

**Issue by afeld** [18F/brand#68]
Just used the Keynote template in a slide deck for the tech talk I just did – very nice! Curious if you have a recommendation for a font to use for code. I ended up using Menlo Bold, which you can see in a couple slides:
- https://speakerdeck.com/aidanfeldman/dabbling-in-docker?slide=9
- https://speakerdeck.com/aidanfeldman/dabbling-in-docker?slide=10

Thoughts?

**Comment by jenniferthibault** [comment]
cc @thecapacity / @vz3 - you put some great options in the channel, I'd love to hear more about how and when you use monospaced fonts in stuff you make. When do _you_ need a font like this? What applications do you use them in, which fonts do you like and why? etc. It will help us look at options.

**Comment by thecapacity** [comment]
I mostly use it for the terminal - but I think that's spilled over into presentations and documents (e.g. disliking it when bullets don't line up even w/ the same length words). I'm pretty used to it (read that as "tolerant") now when making documents, but thought it would be cool if that developer mindset could translate into our 18F approach.

**Comment by afeld** [comment]
[Discussion in Slack](https://18f.slack.com/archives/18f-branding/p1453756285000009)

**Comment by noahmanger** [comment]
I've used [Inconsolata](http://www.levien.com/type/myfonts/inconsolata.html) for a while. It's nice. Giving Input a try now though.

**Comment by rogeruiz** [comment]
I've used [M+ M Type-2](https://mplus-fonts.osdn.jp/design.html#mplus_m2) for the last 4 years and haven't looked back. It has a lot of different weights for emphasis. I use this font for my terminal and also for most text editors that allow me to change the default font face. There is an alternate monospace version called [M+ MN Type-1](https://mplus-fonts.osdn.jp/design.html#mplus_mn1) but I don't like the lowercase `g` as much as M Type-2. It's also open source! :smile:

**Comment by maya** [comment]
The fontstack we use for the web design standards is `Consolas, Monaco, 'Andale Mono', monospace` — which are system fonts. I'm sure there will always be a prettier font out there (hello [Source Code Pro](https://www.google.com/fonts/specimen/Source+Code+Pro)), but this suits us for now. It's not something we overthought too much and rather get the performance benefits of a system font.

**Comment by thecapacity** [comment]
Did anyone take a look at Anonymous: http://www.marksimonson.com/fonts/view/anonymous-pro ?

I think it bridges the "code" (which can sometimes be too blocky) and "presentation" fonts fairly well... it looks similar to the M+ (which looks really nice).
