### ISSUE TITLE
Replace the user-group icon in our Slides template with one that isn't gender biased

### ISSUE THREAD

**Issue by ericronne** [18F/brand#69]
In addition to the role icons play in illustrating a concept, our icons should reflect our values. The highlighted icon below — from our current google slides branded template — has a bit of a sexist slant. We should replace, redrawing if need be.

![image](https://cloud.githubusercontent.com/assets/9259185/12588369/fb3839ec-c41d-11e5-9c4c-69ac47ad3d30.png)

**Comment by ericronne** [comment]
Here are some "people" options offered by our Picons set....

### Picons Thin
![image](https://cloud.githubusercontent.com/assets/9259185/12588433/455157b6-c41e-11e5-8380-c119273e2c4c.png)

### Picons Basic 1
![image](https://cloud.githubusercontent.com/assets/9259185/12588471/62026896-c41e-11e5-8c32-4c96f02a40b6.png)

## Picons Basic 2
![image](https://cloud.githubusercontent.com/assets/9259185/12588480/6dccf560-c41e-11e5-98e2-66f5d19fecc0.png)

**Comment by ericronne** [comment]
Interesting account of how facebook's new icon was developed, fyi ...

https://medium.com/facebook-design/how-we-changed-the-facebook-friends-icon-dc8526ea9ea8#.bsr9p661s

![image](https://cloud.githubusercontent.com/assets/9259185/12588542/b896396c-c41e-11e5-854d-137f4385e776.png)
Middle one reminds me of Moss from IT Crowd

**Comment by mogul** [comment]
I really noticed it in this slide... Look at all those poor women trying to look over the guys' shoulders!
![image](https://cloud.githubusercontent.com/assets/47762/12601818/3ffa0da4-c472-11e5-819e-0631fa53277f.png)

**Comment by NoahKunin** [comment]
I just need some meeples 

https://www.meeplesource.com/proddetail.php?prod=BlueMeeple

**Comment by NoahKunin** [comment]
But seriously, since I brought it up in Slack, one idea I had is if we have a SVG of the generic human in Picons Basic 2 at the far right, what I'd do in AI is clone it twice, drop each icon to 70% scale, put them in the background at 80% opacity, and ship the result.

**Comment by ericronne** [comment]
This would take redrawing to normalize line weights, but for reference...
![image](https://cloud.githubusercontent.com/assets/9259185/12901566/059a012c-ce82-11e5-9770-fb899d74ef9d.png)

@jenniferthibault @rtwell @amberwreed ?
To me the head looks a little cartoony, but it may suffice for now.

![image](https://cloud.githubusercontent.com/assets/9259185/12901618/4024b8c8-ce82-11e5-8c72-7a669f3ab38d.png)

**Comment by amberwreed** [comment]
Agreed. That's why I didn't include it originally. Maybe we can make them
earless heads. :)

On Mon, Feb 8, 2016 at 2:41 PM, Eric Ronne <notifications@github.com> wrote:

> This would take redrawing to normalize line weights, but for reference...
> [image: image]
> <https://cloud.githubusercontent.com/assets/9259185/12901566/059a012c-ce82-11e5-9770-fb899d74ef9d.png>
>
> @jenniferthibault <https://github.com/jenniferthibault> @rtwell
> <https://github.com/rtwell> @amberwreed <https://github.com/amberwreed> ?
> To me the head looks a little cartoony, but it may suffice for now.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/9259185/12901618/4024b8c8-ce82-11e5-8c72-7a669f3ab38d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/brand/issues/69#issuecomment-181603695>.
>



-- 
-------------------------
*Amber Reed*
Experience Designer
18F

**Comment by jenniferthibault** [comment]
Heh! Those ears only bother me when the icon is this large, but when it's icon-sized I'm not too distracted, so don't have strong opinions. What I do like about them is they give the icon _some_ personality. 

Could we make the second meeple (behind) a liiiiiittle larger so that the size difference isn't quite so high contrast? I'm digging how the original icons in Bret's are closer to equal size, which make it easy to use at smaller sizes.

**Comment by AvivaOskow** [comment]
@cmajel @nickttng 
[Team-Replacement-icon.zip](https://github.com/18F/brand/files/3158530/Team-Replacement-icon.zip)

**Comment by cmajel** [comment]
Adding some updates to this issue

We now have:
- Avataaars for illustrating people and emotion
![Screen Shot 2020-06-11 at 12 37 06 PM](https://user-images.githubusercontent.com/2374206/84415163-5b3d7600-abe0-11ea-8fc4-cc6f66a490dd.png)

- A new icon set based on Feather that's based on a simplified user icon
![Screen Shot 2020-06-11 at 12 36 33 PM](https://user-images.githubusercontent.com/2374206/84415137-524ca480-abe0-11ea-9564-6005fc71e40c.png)

I'm going to close this for now as we've retired the icon that started this conversation, and are now offer these options in our slide deck. However, I'd encourage us to continue thinking about ways we can improve our illustrations and icon set to be more inclusive. 

Please open a new issue if you have suggestions or feedback!
