### ISSUE TITLE
Design the 18F handbook

### ISSUE THREAD

**Issue by ericronne** [18F/brand#70]
Once we've been able to fully translate the brand look into web form, let's be sure to bring the handbook into line with it!

https://projects.invisionapp.com/share/HT5OCG8J7#/screens/129119843

**Comment by ericronne** [comment]
From Michael Torres' 1.26.16 email announcement ...

As announced in prior team meetings, the 18F Handbook was created as the canonical place for new and existing 18F employees to learn what they need to know to be productive. Much of the content in our Handbook originated in the Hub. Now that we’ve got much of the Handbook content written and edited, we’re moving to building a better interface to explore what the Handbook has to offer. As a reminder, if you’d like to contribute to the Handbook, the easiest way is by tagging things with an :evergreen-tree: in Slack. 

Right now the Handbook only exists in a GitHub repo, but we’re planning to improve that experience very soon! Here is a preview:
<img width="544" alt="screen shot 2016-01-19 at 1 57 08 pm" src="https://cloud.githubusercontent.com/assets/9259185/12591312/bc296c58-c42c-11e5-8f5d-8b6571f8304c.png">
![25a8ffa9-c712-43ea-9def-3414fecdff42](https://cloud.githubusercontent.com/assets/9259185/12591315/c15257a8-c42c-11e5-9841-6b68027621f7.png)

The search bar at the top of these pages represents the the next iteration of the Hub: a place where people can find all 18F content, wherever that content may live. Our next steps are to remove any duplicate content (between the Handbook and the Hub) and to re-architect the Hub so that it will better surface and display all forms of 18F documentation, including our Handbook, Team Graph, and our Guides. 

Here is a preview of the Hub homepage concept:
![1e7c121f-765f-474a-908a-886d89e1d14d](https://cloud.githubusercontent.com/assets/9259185/12591322/cc859a0e-c42c-11e5-8a8c-35478d8e195d.png)
![7175159a-4764-4fff-a2eb-069abaf01802](https://cloud.githubusercontent.com/assets/9259185/12591327/d42948c8-c42c-11e5-8246-2d978bc0c2ae.png)

We have a lot of ideas backed by a lot of research. We’ve set up an interactive mock so you can see at a high level how these pages are related to each other. We welcome any comments or feedback. You can leave them in invision, or in the #hub channel.

Thank you!

The Hub Team (@hub-team)

**Comment by melodykramer** [comment]
. just to follow this. And pinging @andrewmaier too.

**Comment by jenniferthibault** [comment]
Closing — since this is now the TTS handbook other discussion are going on about how to appropriately style it in https://github.com/18F/handbook/issues/1034
