### ISSUE TITLE
Create a poster/wallpaper series based on our values

### ISSUE THREAD

**Issue by ericronne** [18F/brand#74]
quick example ...

![18fdesktop-quote-collab-tbolt](https://cloud.githubusercontent.com/assets/9259185/12647451/d62fb890-c59a-11e5-92d6-c53d2714aafe.png)

**Comment by NoahKunin** [comment]
:heart_eyes:

**Comment by jenniferthibault** [comment]
Closing until we observe a need for this in the current organization

**Comment by annepetersen** [comment]
This has come up recently in Slack due to some of our old posters. I wonder if a refreshed series would be appreciated?
