### ISSUE TITLE
Add keynote-to-ppt-to-google slides conversion trick to instructions

### ISSUE THREAD

**Issue by ericronne** [18F/brand#78]
Michael Cata clued @jenniferthibault into this trick. Add it to our brand kit instructions?

"Even if you make a slide deck in Keynote, you can easily turn it into a Google Slides deck by exporting a PPT file from Keynote, then importing that into Google Slides. It takes very small cleanup (I only had to adjust two shapes and a few type sizes) and works really fast." -jt

**Comment by jenniferthibault** [comment]
Closing until we observe a need for this in the current organization
