### ISSUE TITLE
Google slides template does not seem to exist

### ISSUE THREAD

**Issue by toolness** [18F/brand#90]
The [Using 18F's Brand Templates PDF](https://pages-staging.18f.gov/brand/assets/dist/Using_18Fs_Templates.pdf) claims the following on page 6, step 2:

> In the search bar select 18F_Theme_GoogleSlides. Select and import theme.

No such theme appears to exist. There is something called "18F Deck TEMPLATE" that looks like it's the right theme--the thumbnail looks exactly right, at least--but when I double-click on it, I'm presented with one option called "Simple Light", which appears to be the vanilla Google theme.

This leads me to believe I should just make a copy of "18F Deck TEMPLATE" instead of going through "Import Theme", but the funny thing is that I can't actually *find* it via **File -> Open**--it only shows up when I click "Import Theme". :persevere:

**Comment by toolness** [comment]
Oh, looks like the latest template is here: https://docs.google.com/presentation/d/1AtTYOd0jjZnKUhBQ0c5oX5mmHQ4bd_Q2KvrdsQMw2nk/edit#slide=id.p

**Comment by jenniferthibault** [comment]
Resolved by https://github.com/18F/brand/pull/97
