### ISSUE TITLE
Keynote ZIP contains two copies of the same presentation

### ISSUE THREAD

**Issue by toolness** [18F/brand#91]
They don't have the exact same file size--one is a few kilobytes larger--but there are two keynote presentations in [`assets/dist/18F_Keynote.zip`](https://pages-staging.18f.gov/brand/assets/dist/18F_Keynote.zip):

1. `18F_Template_2016-03-29.key`
2. `keynote09_18F_Template_2016-03-29.key`

Both appear to be 32-slide presentations with the same slides, and are about 3.8 MB each. Removing one would make the ZIP file smaller and reduce confusion--or, if there's a good reason that both are in there, perhaps provide a README with guidance?

**Comment by jenniferthibault** [comment]
Sharp detective work! The second item there is for an older version of Keynote, which some users at 18F have if they haven't upgraded their operating system to El Capitan. Usually when they haven't upgraded their OS, it's for a reason, and we didn't find that needing the latest keynote template was compelling enough to counter their reasons for not upgrading 😄 

I've updated the readme to reflect that, and other recent changes in https://github.com/18F/brand/pull/98
