### ISSUE TITLE
Add detail about custom typography

### ISSUE THREAD

**Issue by jenniferthibault** [18F/brand#95]
- Draft copy about what we customized and why we did it: @rtwell 
- Research requirements for licensing and referencing the original open source font:  @thisisdano

I'm not trying to stack everything into one, but if you want to look at another issue filed about the typography for other context, there's also this one about including an image of our font to make it more visually appealing and easier to find the section when you're scanning the page: https://github.com/18F/brand/issues/60

**Comment by rtwell** [comment]
DRAFT:
Once 18F decided you utilize Nimbus, we ran into a two issues with that particular font:
1) Some software programs rendered a uppercase "N" followed by a lowercase "o", the "No" glyph would be automatically substituted, like so:
![image](https://cloud.githubusercontent.com/assets/12564977/15724714/f8263c50-280d-11e6-9396-bbe0d1a3920e.png)
We disabled that behavior. 
2) Since our name "18F" could be regular occurrence with some of our documentation, we wanted to ensure the characters "1" and "8" would properly kern. Tabular numerics are built to vertically stack evenly, however, the number 1 does not consume as much horizontal space as any other numeric. As a result, when tabular numerics appear in sequence like 18F, there is a visual disconnect. We addressed this by slightly adjusting the kerning pairs that include the number 1, as seen here:
![image](https://cloud.githubusercontent.com/assets/12564977/15725036/849986fa-280f-11e6-8f86-414d9e5a6285.png)
@jenniferthibault

**Comment by thisisdano** [comment]
I think we just need to make sure that any modified version of Nimbus that we distribute has a unique name distinct from `Nimbus Sans`. `Nimbus Sans 18F` would satisfy that requirement. We should also have a link to the original typeface and a note that our new face uses the same license as the original: `GNU General Public License`.

The relevant part of the GNU GPL license (http://www.gnu.org/copyleft/gpl.html):

- - -
- The work must carry prominent notices stating that you modified it, and giving a relevant date.
- The work must carry prominent notices stating that it is released under this License and any conditions added under section 7. This requirement modifies the requirement in section 4 to “keep intact all notices”.
- You must license the entire work, as a whole, under this License to anyone who comes into possession of a copy. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.
- If the work has interactive user interfaces, each must display Appropriate Legal Notices; however, if the Program has interactive interfaces that do not display Appropriate Legal Notices, your work need not make them do so.

- - -

Changing the name in the fonts themselves will also help with any font conflicts where, say, the original version of Nimbus exists on a user's system, and the modified is called via `@font-face`. You could get display inconsistency.

**Comment by rtwell** [comment]
very thoughtful, per usual @thisisdano. +1!

**Comment by jenniferthibault** [comment]
What are next steps for this @thisisdano ?

**Comment by thisisdano** [comment]
- [ ] rename font
- [ ] include link/notice about the GNU GPL wherever we distribute the font
- [ ] include notice that our version is a based on Nimbus Sans

This kinda text might do it:

> Nimbus 18F was created in 2016 [and modified in NNNN]. It is based on Nimbus Sans [link], originally created by URW++, and is distributed under the GNU General Public License [link].

**Comment by jenniferthibault** [comment]
Awesome, thank you for distilling that down for my foggy brain @thisisdano !

Do you have capacity to take those on? I'd be glad to be a reviewing or brainstorming resource for you.

**Comment by thisisdano** [comment]
Yes, I can do this. (I think!) The re-naming is the tricky part, but I think I can so it with the software I have.

**Comment by jenniferthibault** [comment]
I just added the legal copy into the doc that frames the site for public-readiness.
@rtwell don't worry, haven't forgotten your "What we changed" section, just staying laser focused on what bits _need_ to be in (legally) in this case.
How goes the renaming, @thisisdano

**Comment by jenniferthibault** [comment]
To catch this issue up to speed with recent events, here's a brief update to be followed with action items in new issues:
- Nimbus Sans (both customized and original files) have shown weird, insurmountable rendering issues when implemented online. We think that the problem is with the source files themselves, not with the implementation approaches.
- Using and customizing Nimbus, as a open source font, showed how 18F values open source products. Buying a Nimbus Sans font from Typekit squashes this benefit, but would solve the rendering problem. We ruled out this option and are in favor of replacing our main font with a closely related system font: Helvetica with an Arial fallback.

I'll be filing new issues to update our assets and documentation.
