### ISSUE TITLE
Update logo on Gravatar

### ISSUE THREAD

**Issue by afeld** [18F/brand#99]
[Gravatar](http://en.gravatar.com/) is still using the old logo for `devops@gsa.gov`, but I don't have the login information to change it. Maybe check with #infrastructure?

**Comment by jenniferthibault** [comment]
Thanks for pointing this out! I pinged #infrastructure and Noah Kunin updated it. Is there a place I could see this to verify without logging in ?

**Comment by afeld** [comment]
Looks good, thanks!

>  Is there a place I could see this to verify without logging in ?

Yep! https://en.gravatar.com/site/check/ using `devops@gsa.gov`.
